version: '2.3'
services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      backend:
        condition: service_healthy
      archiver:
        condition: service_started
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf.dev:/etc/nginx/nginx.conf
      - data-dev:/storage
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - frontend-assets-dev:/app/dist:ro
      - data-dev:/storage
    sysctls:
      net.core.somaxconn: 500
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m
      timeout: 2m
      retries: 3
      start_period: 30s
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: frontend
    env_file:
      - .env.dev
    volumes:
      # quick hack to allow webpack config updates between reups
      - ./client/webpack.config.js:/app/webpack.config.js
      - ./client/webpack.dev.js:/app/webpack.dev.js
      - ./client/src:/app/src
      - ./client/static:/app/static
      # and another one for misc configs
      - ./client/configs:/app/configs
      - frontend-assets-dev:/app/dev
    stdin_open: true
  archiver:
    build:
      context: ./archiver
      dockerfile: Dockerfile.dev
    container_name: archiver
    env_file:
      - .env.dev
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    # environment:
    volumes:
      - ./archiver:/app
      - data-dev:/storage
    sysctls:
      net.core.somaxconn: 40000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/development"]
      interval: 1m
      timeout: 2m
      retries: 3
      start_period: 30s
  redis:
    image: redis:6.2.0
    container_name: redis
  database:
    image: healthcheck/postgres
    container_name: database
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db-data-dev:/var/lib/postgresql/data/
    restart: unless-stopped
    # ports:
    #  - 5432:5432
  autoheal:
    restart: always
    container_name: kemono-autoheal
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  # If you need to store your volumes manually, uncomment the "driver_opts" lines and specify your "device" location.
  db-data-dev:
    driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: "/mnt/slab1/kemono-db-dev"
  data-dev:
    driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: "/mnt/slab1/kemono-dev"
  frontend-assets-dev:
    driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: "/mnt/slab1/kemono-assets-dev"
